# fly.toml app configuration file generated for f2-shopping-list on 2023-10-20T13:37:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "f2-shopping-list"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
